name: PubSub Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pubsub-emulator:
        image: gcr.io/google/cloud-sdk:latest
        ports:
          - 8085:8085
        options: >-
          bash -c "gcloud components install beta pubsub-emulator --quiet && gcloud beta emulators pubsub start --host-port=0.0.0.0:8085"    

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.11.1"

    - name: Install dependencies
      run: npm install

    - name: Set Pub/Sub Emulator Host
      run: echo "PUBSUB_EMULATOR_HOST=localhost:8085" >> $GITHUB_ENV

    - name: Run tests
      run: node index
