name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.11.1"

    - name: Install dependencies
      run: npm install

    - name: Build Pub/Sub Emulator Docker Image
      run: docker build -t pubsub-emulator .

    - name: Start Pub/Sub Emulator
      run: |
        docker run -d -p 8085:8085 --name pubsub-emulator pubsub-emulator

    - name: Set Pub/Sub Emulator Host
      run: echo "PUBSUB_EMULATOR_HOST=localhost:8085" >> $GITHUB_ENV

    - name: Wait 10 seconds
      run: sleep 10

    - name: Run tests
      run: node index.js

    # prepare SSH env in case of failure
    - name: Prepare environment setup script
      if: failure()
      run: |
        echo "export PATH=/opt/hostedtoolcache/node/20.11.1/x64/bin:\$PATH" > $HOME/env_setup.sh

    # ssh access (in case of failure)
    - name: Setup zsh session
      uses: brunokrebs/action-oh-my-zsh@main
      if: failure()
      with:
        ngrok-auth-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        ssh-timeout: 120
        allow-pr-owner: true
